### ISSUE TITLE
Typos in the command palette

### ISSUE THREAD

**Issue by BNAndras** [exercism/vscode-exercism-cli#3]
When viewing the Exercism commands in the command palette, Exercism is misspelled in "Check the installed Exericsm CLI" and "Upgrade the Exericsm CLI"

![image](https://user-images.githubusercontent.com/20251272/192660451-b3c50955-bf3b-4c46-b81b-eaff3cebdd0a.png)

**Comment by SleeplessByte** [comment]
Fixed in #4 and released as 0.2.1!
